vmware/powershell-module-for-vmware-cloud-foundation-reporting

.ci/pester.tests.ps1
.github/workflows/ci-module.yml

Adds **basic** CI checks for module import and manifest check when changed are made to .`psm1` and `.psd1` files only.
Please describe: `ci`

ci(module): add basic module ci

---

CHANGELOG.md

docs: add `CHANGELOG.md`

---

VMware.CloudFoundation.Reporting.psd1

- Updates the module metadata with links back to the GitHub project.
- Bumps from `v1.0.4.1001` to `v1.0.5.1001.`

chore: update module metadata

---

VMware.CloudFoundation.Reporting.psm1

- Add message output to confirm modules are installed and prereq is met
Issue Number: Closes #20 

feat: enhancements to Test-VcfReportingPrereq

---

VMware.CloudFoundation.Reporting.psm1

Updates `Test-VcfReportingPrereq` to display the current installed module version versus the minimum version in the module requirements array.
Closes [#26](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-reporting/issues/26)

fix: update prerequisites version check

---

VMware.CloudFoundation.Reporting.psm1

Update the following cmdlets for NSX:VC 1:many:
- `Request-NsxtVidmStatus`
- `Request-NsxtComputeManagerStatus`
Closes #22

fix: nsx one-to-many

---

.github/ISSUE_TEMPLATE/bug.yml

Updates the bug report issue template to include all dependences in the form.

chore(gh): update bug report template

---

VMware.CloudFoundation.Reporting.psm1

- Adds `Request-EsxiOverview` function to return the high-level status of each ESXi host in a system.
- Updates `Publish-VcfSystemOverview` to include the ESXi Host Overview.
Closes #23

feat(overview): add esxi hosts

---

README.md

Update the `README.md` to include PowerShell module dependency updates for release

docs(release): update `README.md`

---

CHANGELOG.md

Updates `CHANGELOG.md` for release.

docs(release): update `CHANGELOG.md`

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Update `Publish-` functions for password policies
- Updated Password Policy Report

feat: add password policy functions

---

VMware.CloudFoundation.Reporting.psm1

Improvements around code efficiency:
- Added $commandSwitch to create the -allDomains or -workloadDomain and -failureOnly input for a command
- Refactored all `Publish-` calls to use $commandSwitch resulting in single command per element and reduction of ten lines of code per element
- 30% reduction in lines of code for Invoke-VcfAlertReport

feat: improve code efficiency of Invoke-VcfAlertReport

---

VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

Improvements around code efficiency:
- Added $commandSwitch to create the -allDomains or -workloadDomain switch
- Refactored all Publish- calls to use $commandSwitch resulting in single command per element and reduction of ten lines of code per element
- 25% reduction in lines of code for `Invoke-VcfPasswordPolicy`
Signed-off-by: Gary Blake gblake@vmware.com

feat: improve code efficiency of `Invoke-VcfPasswordPolicy`

---

VMware.CloudFoundation.Reporting.psm1

- Code efficiency for `Publish-StorageCapacityHealth`

feat: code efficiency for Publish-StorageCapacityHealth

---

README.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

Updates `PowerValidatedSolutions` from v1.10.0 to v2.0.0 for the v1.0.6 release.
Closes #67

chore(deps): bump `PowerValidatedSolutions` from v1.10.0 to v2.0.0

---

README.md
VMware.CloudFoundation.Reporting.psd1

- Updated GUID in `VMware.CloudFoundation.Reporting.psd1`
- Updated copyright dates in `README.md`

chore(release): prepare release

---

VMware.CloudFoundation.Reporting.psm1

`Out-File` is used to create Json files in `Publish-*` cmdlets. We need to specify encoding for the generated file so that python script can read it properly. Needed for HRM.

enhancement: specify encoding for `Out-File`

---

VMware.CloudFoundation.Reporting.psd1

- Updated the description for PS Gallery

chore: update description for ps gallery

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Updates `PowerVCF` from v2.2.0 to v2.3.0.
- Bumps the module version to v2.0.0.1010.

 chore(deps): bump `PowerVCF` from 2.2.0 to 2.3.0

---

CHANGELOG.md
README.md
VMware.CloudFoundation.Reporting.psd1

Updates the `README.md` for the following:
- Removes the Password Policy report. Ref: #118
- Updates the PowerShell module dependencies. Ref:  #117
- `PowerVCF` 2.3.0
- `PowerValidatedSolutions` 2.2.0
- `VMware.vSphere.SsoAdmin` 1.3.9
- `VMware.PowerCLI` 13.0.0
- Updates the minimum supported VMware Cloud Foundation version. Ref: #117
- Updates the use of `Test-VcfReportingPrereq`. Ref:  #117
- Updates the use of `Invoke-VcfHealthReport`. Ref:  #113
- Updates `CHANGELOG.md` with v.2.0.0 release date.
- Updates the module …

docs: update `README.md`

---

VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

Updates `Request-NetworkOverview` to resolve a bug introduced in #130.
Related #130 
```powershell
PS F:\VMware.CloudFoundation.Reporting> Request-NetworkOverview -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1!
NSX Manager Cluster FQDN : sfo-m01-nsx01.sfo.rainpole.io
Version                  : 4.1.0.0.0-21180617
Domain Name              : sfo-m01
Domain Type              : management …
```

fix: update `Request-NetworkOverview`

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Updates `Publish-NsxtTier0BgpStatus` to format the HTML correctly in the event that $nsxtTier0BgpStatus.Count for a workload domain is not greater than 0.
- Updates module version to v2.1.0.1006.
- Updates the `CHANGELOG.md`.
Related #106 
**Before:**
**After**:

fix: update `Publish-NsxtTier0BgpStatus`

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Updated "NSX-T Data Center" to "NSX" product name.
- Updated "NSX Manager instance" to "NSX Manager cluster".
- Updated "NSX Managers (Local)" to "NSX Local Managers".
- Updated "from NSX Manager" to "from an NSX Manager".
- Updated module version from v2.1.0.1006 to v2.1.0.1007.
Please describe: `chore`

chore: update nsx product terms

---

VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Updated all examples to use admin@local API credentials.
- Updated module version from v2.1.0.1007 to v2.1.0.1008.
Please describe: `chore`

chore: update example credentials

---

VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Updated header comments.
- Updated `} else {` and `} elseif {` as needed.
- Updated `Foreach` to `foreach`.
- Updated module version from v2.1.0.1008 to v2.1.0.1009.

chore: code formatting

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Cherry-picked 430661eb2f34f07a220d2020b17bc879fa78cb8b.
- Updated module version from v2.1.0.1009 to v2.1.0.1010.

fix: remove sos elements based on version

---

CHANGELOG.md
README.md
VMware.CloudFoundation.Reporting.psd1

- Reviewed and Updated README.md
- Updated GUID in VMware.CloudFoundation.Reporting.psd1
- Updated release date CHANGELOG.md

chore: release updates

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
docs/index.md
docs/snippets/install-module.ps1

- Updated `PowerValidatedSolutions` from v13.0.0 to v13.1.0
- Updated `VMware.PowerCLI` from v2.5.0 to v2.6.0. 
- Updated module versions in `docs/snippets/install-module.ps1` 
- Added PowerShell Gallery downloads badge to the `docs/index.md` 

chore: release preparation

---

docs/documentation/functions/Publish-DnsHealth.md
docs/documentation/functions/Publish-EsxiHealth.md
docs/documentation/functions/Publish-HardwareCompatibilityHealth.md
docs/documentation/functions/Publish-NsxtEdgeClusterHealth.md
docs/documentation/functions/Publish-NtpHealth.md
docs/documentation/functions/Publish-PasswordHealth.md
docs/documentation/functions/Publish-PingConnectivityHealth.md
docs/documentation/functions/Publish-ServiceHealth.md
docs/documentation/functions/Publish-VcenterHealth.md
docs/documentation/functions/Publish-VersionHealth.md
docs/documentation/functions/Publish-VsanHealth.md
docs/documentation/functions/Publish-VsanStoragePolicy.md

Updates syntax for publish cmdlets that use the JSON from the SoS Health Summary.
Closes #201

docs: update publish cmdlet syntax

---

LICENSE
Makefile
NOTICE
README.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

Updates the copyright to 2023-2024 in preparation for the next release.

chore: update copyright

---

CHANGELOG.md
docs/index.md

chore: release v2.6.0
