README.md
VMware.CloudFoundation.Reporting.psm1

- Removes the `Test-VcfReportingPrereq` from the `Invoke-*` cmdlets, blocking running the cmdlets.
- Updates the `README.md` for prerequisites verification.
- Updates the module to align to a minimum of PowerValidatedSolutions 1.7.0 to align with the current `README.md`.

fix: remove invoke prerequisites check

---

VMware.CloudFoundation.Reporting.psm1

Added Support for vRLI, vROPS, vRA, WSA under Request-LocalUserExpiry. Function already works just needed to add other product names to pass into the Component section of the output.

feat: Add vRealize Suite Support for Request-LocalUserExpiry

---

VMware.CloudFoundation.Reporting.psm1

Bumps the following depedencies:
- `PowerValidatedSolutions` from 1.7.0 to 1.10.0
- `VMware.PowerCLI` from 12.4.1 to 12.7.0
- `VMware.vSphere.SsoAdmin` from 1.3.7 to 1.3.9
Updates `Test-VcfReportingPrereq` to to break versus exit if version does not meet requirements so that the error is displays; otherwise, the PowerShell console will close.
Replaces local `getNsxtServerDetail` function with `Get-NsxtServerDetail` function exported from PowerValidatedSolutions.
**Type …

chore(deps): bump dependencies

---

VMware.CloudFoundation.Reporting.psm1

Adds support for including the number of ESXi hosts per cluster in System Overview Report.
Closes #45 
Standard Output:
Anonymized Output:

feat(overview): add cluster host count

---

VMware.CloudFoundation.Reporting.psm1

When calling  `Publish-NsxtHealth, `Publish-NsxtCombinedHealth` is passing $jsonFilePath instead of $json
Issue Number: Closes #58 

fix: error in variable passed to Publish-NsxtHealth

---

VMware.CloudFoundation.Reporting.psm1

Improvements around code efficiency:
- Added $commandSwitch to create the -allDomains or -workloadDomain and -failureOnly input for a command
- Refactored all `Publish-` calls to use $commandSwitch resulting in single command per element and reduction of ten lines of code per element
- 50% reduction in lines of code for Invoke-VcfHealthReport

feat: improve code efficiency of Invoke-VcfHealthReport

---

VMware.CloudFoundation.Reporting.psm1

Improvements around code efficiency:
- Added $commandSwitch to create the -allDomains or -workloadDomain switch
- Refactored all `Publish-` calls to use $commandSwitch resulting in single command per element and reduction of ten lines of code per element
- 30% reduction in lines of code for `Invoke-VcfConfigReport`

feat: improve code efficiency of `Invoke-VcfConfigReport`

---

VMware.CloudFoundation.Reporting.psm1

Updates `Request0VcenterOverview` to use the PowerVCF cmdlets to return the workload domain's cluster and host counts from the SDDC Manager inventory versus directly from the vSphere inventory. This will ensure that the host count does not include any HCX nodes and addresses #44.
Closes #44 

fix(overview): exclude hcx hosts

---

VMware.CloudFoundation.Reporting.psm1

Fixing issue: [#74 - Request-NsxtEdgeUserExpiry function does not work if NSX Edge root password is different from NSX Manager root password ](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-reporting/issues/74)
Fixed function to use the correct variable (FQDN) in order to get NSX Edge password 
Resolves #74

fix: gh-74

---

VMware.CloudFoundation.Reporting.psm1

Adds CPU Cores per Socket to the ESXi Host Overview on the overview report.
Related: #78 (_Does not close_.)

feat: add cpu cores per socket

---

VMware.CloudFoundation.Reporting.psm1

Updated `Publish-*` cmdlets to support JSON generation for:
- `Publish-BackupStatus`
- `Publish-NsxtTransportNodeStatus`
- `Publish-NsxtTier0BgpStatus`
- `Publish-SnapshotStatus`
- `Publish-LocalUserExpiry`
- `Publish-StorageCapacityHealth`
Added 2 additional functions:
- `Publish-NsxtHealthNonSOS`
- `Publish-ComponentConnectivityHealthNonSOS`
Signed-off-by: bhumitra nagar <bnagar@vmware.com>
Closes #37
**Breaking …

feat: update `Publish-*` methods for JSON generation

---

VMware.CloudFoundation.Reporting.psm1

Resolves an issue with the display name of the vRealize Log Insight product name in the **vRealize Suite Overview** due to an upstream error in the `.SYNOPSIS` of `Get-VCFvRLI` in `PowerVCF`.
This change may allow future versions of the module to adopt the rebranding to Aria Suite ahead of PowerVCF.

fix: vrealize product display name

---

VMware.CloudFoundation.Reporting.psm1

Adds an option to `Request-ESXiOverview` to report on the VCF+ subscription cores and export the results to CSV.
Adds `Start-CreateOutputCsvDirectory` function.
Closes #78 
```powershell
PS F:\VMware.CloudFoundation.Reporting> Request-EsxiOverview -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1! -subscription -outputCsv F:\Reporting\csv …
```

feat: add vcf+ subscription cores

---

VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Update `Publish-vCenerHealth` to correctly link and display the vCenter Server Ring Topology Health from SoS.
- Bump to 1.1.0.1001
Closes #91

fix: vcenter server ring topology

---

VMware.CloudFoundation.Reporting.psm1

Updates the backup message to remove the SDDC Manager FQDN f when backups are located on the SDDC Manager. Must be addressed for HRM alerts.

fix: update backup message

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

=In order to have a good experience with our community, we recommend that you read the [contributing guidelines](https://github.com/vmware/powershell-module-for-cloud-foundation-reorting/blob/main/CONTRIBUTING_DCO.md) for making a pull request.
Removes the `sddcManagerRootPass` parameter from `Invoke-VcfHealthReport` cmdlet as it uses the refactored `Request-SoSHealthJson` cmdlet.
Issue Number: #102 

refactor: remove `sddcManagerRootPass` from `Invoke-VcfHealthReport`

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Updates `Publish-PasswordHealth` to return the results from the SoS Health Summary JSON data. #90
- Updates `Invoke-VcfHealthReport` to use the `Publish-PasswordHealth` cmdlet. #90
- Updates `Publish-PasswordHealth` to include an "Expires In (Days)" column. #40
- Removes `Publish-LocalUserExpiry` in favor of the `Publish-PasswordHealth` cmdlet. #90
- Bumps the module version to v2.0.0.1004.
Closes #90 
Closes #40
Closes …

reactor: transition to `Publish-PasswordHealth`

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- **Breaking**: Updates `Invoke-VcfHealthReport` to use `-localUser` and `localPass` parameters instead of `-SddcManagerRootPass`. Examples use the local `vcf` user account for the SDDC Manager virtual appliance.
- **Breaking**: Updates `Publish-StorageCapacityHealth` to use `-localUser` and `localPass` parameters instead of `-rootPass`. Examples use the local `vcf` user account for the SDDC Manager virtual appliance.
- **Breaking**: Updates `Request-SddcManagerStorageHealth` to use `-localUser` and `localPass` parameters …

refactor: remove SDDC Manager `root` password dependency

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- **Breaking**: Removes `Invoke-VcfPasswordPolicy` and supporting content. Please use the `VMware.CloudFoundation.PasswordManagement` module.
- Bumps the module version to v2.0.0.1006.
Documentation will be updated for the v2.0.0 release in a separate pull request.

refactor: remove `Invoke-VcfPasswordPolicy` and supporting content

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psm1

- Removes `Request-LocalUserExpiry` which supported the `Publish-LocalUserExpiry` cmdlet. 
- Removes `Request-SddcManagerUserExpiry` which supported the `Publish-LocalUserExpiry` cmdlet.
- Removes `Request-vCenterUserExpiry` which supported the `Publish-LocalUserExpiry` cmdlet.
- Removes `Request-NsxtManagerUserExpiry` which supported the `Publish-LocalUserExpiry` cmdlet.
- Removes `Request-NsxtEdgeUserExpiry` which supported the `Publish-LocalUserExpiry` cmdlet.
- Removes `Request-Request-vRslcmUserExpiry` which …

refactor:  remove `Publish-LocalUserExpiry` support functions

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Added `Publish-VersionHealth` to return the version health from the SoS Health Summary JSON data.
- Updated `Invoke-VcfHealthReport` to include the version health using the `Publish-VersionHealth` cmdlet.
- Fix typos.
- Bumps the module version to v2.0.0.1008.
Ref: #41
Related #41 
```powershell
PS F:\> Publish-VersionHealth -json …
```

feat: add version health

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Updated `Publish-VsanHealth` to include the results for capacity utilization and the active resysc of objects.
- Bumps the module version to v2.0.0.1009.
Ref: #103
Closes #103 
```powershell
PS F:\> Publish-VsanHealth -json F:\Reporting\HealthReports\sfo-vcf01-all-health-results.json
Component Resource     Alert  Message
--------- --------     -----  -------
vCenter   sfo-m01-cl01 - …
```

feat: add vsan cluster health checks

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Added component size checks (e.g., tiny, x-small, small, etc...) for vCenter Server instances and NSX Local Manager clusters to the overview report.
- Updates `CHANGELOG.md`
- Updates module version from v2.1.0.1001 to v2.1.0.1002.
Closes #71 
```powershell
PS F:\> Request-VcenterOverview -server sfo-vcf01.sfo.rainpole.io -user admin@local -pass VMw@re1!VMw@re1!
vCenter Server FQDN : sfo-m01-vc01.sfo.rainpole.io …
```

feat: add component size checks

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Updated `Request-VcenterAuthentication` to support isolated workload domains.
- Updated `Request-DatastoreStorageCapacity` to support isolated workload domains.
- Updated `CHANGELOG.md`.
- Updated module version from v2.1.0.1002 to v2.1.0.1003.
Ref: #106
**Results**: Isolated Workload Domains
```powershell
PS C:\Users\Administrator> Request-VcenterAuthentication -server sfo-vcf01.sfo.rainpole.io -user admin@local …
```

refactor: isolated workload domains

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Added `Publish-PingConnectivityHealth` to return the ping connectivity health from the SoS Health Summary JSON data.
- Updated `Publish-ComponentConnectivityHealth` to include the ping connectivity health using the `Publish-PingConnectivityHealth` cmdlet.
- Updated `CHANGELOG.md`.
- Updated module version from v2.1.0.1003 to v2.1.0.1004.
In order to have a good experience with our community, we recommend that you read the [contributing guidelines] …

feat: add ping connectivity

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

Added support for use of secure strings for sensitive parameters.
Closes #195

feat: add secure strings for sensitive parameters

---

docs/documentation/getting-started/alert-report.md
docs/documentation/getting-started/configuration-report.md
docs/documentation/getting-started/health-report.md
docs/documentation/getting-started/overview-report.md
docs/documentation/getting-started/upgrade-precheck-report.md
docs/install.md
docs/update.md
mkdocs.yml

Updates the documentation to provide instructions for:
- Connected Environment (internet access)
- Disconnected Environment (dark-site / air-gapped)

docs: update for connected and disconnected

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1
docs/documentation/functions/Publish-EsxiConnectionHealth.md
docs/documentation/functions/Publish-SddcManagerFreePool.md
docs/documentation/functions/Publish-VmConnectedCdrom.md

1. Updated the following cmdlets to generate JSON output:
- `Publish-VmConnectedCdrom`
- `Publish-EsxiConnectionHealth`
- `Publish-SddcManagerFreePool`
2. Updated cmdlet documentation and examples.
Ran `Publish-SnapshotStatus`, `Publish-EsxiConnectionHealth` and `Publish-SddcManagerFreePool` cmdlets with
`[-outputJson \'<String'>]` parameter. As result respective JSONs were generated.

feat: add support for additional json outputs

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

Added information in the HTML report if a vCenter Server authentication fails to be caught.
Closes #146

fix: add connection check

---

CHANGELOG.md
VMware.CloudFoundation.Reporting.psd1
VMware.CloudFoundation.Reporting.psm1

- Updated `Invoke-VcfHealthReport` cmdlet to handle . or - in the report path.
- Updated `Invoke-VcfAlertReport` cmdlet to handle . or - in the report path.
- Updated `Invoke-VcfConfigReport` cmdlet to handle . or - in the report path.
- Updated `Invoke-VcfUpgradePrecheck` cmdlet to handle . or - in the report path.
- Updated `Invoke-VcfOverviewReport` cmdlet to handle . or - in the report path.
Closes #216

fix: report output failing
